project/Clase/urls.py
from django.urls import path

from . import views

app_name = "Clase"

urlpatterns = [
    path('', views.home, name="home"),
    path('comision_create/', views.create, name="comision_create"),
    path('estudiante_create/', views.estudiante_create, name="estudiante_create"),
    path('estudiante_home/', views.estudiante_home, name="estudiante_home"),
    path('profesor_home/', views.profesor_home, name="profesor_home"),
    path('profesor_create/', views.profesor_create, name="profesor_create"),
    path('curso_home/', views.curso_home, name="curso_home"),
    path('curso_create/', views.curso_create, name="curso_create"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path("Clase/", include("Clase.urls")),
]

project/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.home, name="home"),
]

project/Clase/models.py
from django.db import models

class Curso(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.nombre


class Estudiante(models.Model):
    nombre = models.CharField(max_length=200)
   
    def __str__(self) -> str:
        return self.nombre

class Profesor(models.Model):
    nombre = models.CharField(max_length=200)
    
    def __str__(self) -> str:
        return self.nombre
    
class Comision(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    curso = models.ForeignKey(Curso, on_delete=models.SET_NULL, null=True, blank=True)
    profesor = models.ForeignKey(Profesor, on_delete=models.SET_NULL, null=True, blank=True)
    estudiante = models.ManyToManyField(Estudiante)

    def __str__(self) -> str:
        return str(self.nombre)

project/core/models.py
from django.db import models

# Create your models here.

project/Clase/forms.py
from django import forms

from . import models

class ComisionForm(forms.ModelForm):
    class Meta:
        model = models.Comision
        fields = '__all__'

class EstudianteForm(forms.ModelForm):
    class Meta:
        model = models.Estudiante
        fields = '__all__'

class ProfesorForm(forms.ModelForm):
    class Meta:
        model = models.Profesor
        fields = '__all__'

class CursoForm(forms.ModelForm):
    class Meta:
        model = models.Curso
        fields = '__all__'

project/Clase/views.py
from django.shortcuts import render, redirect

from . import models

from .forms import ComisionForm, EstudianteForm, ProfesorForm, CursoForm


def home(request):
    query = models.Comision.objects.all()
    context = {"comisiones": query}
    return render(request, "Comision/index.html", context)

def create(request):
    if(request.method == "POST"):
        form = ComisionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Clase:comision_create")
        else:
            form2 = ComisionForm()
            return render(request, "Comision/create.html", {"error": form.errors, "form": form2})
    else:
        form = ComisionForm()
        return render(request, "Comision/create.html", {"form": form})
    
def estudiante_home(request):
    query = models.Estudiante.objects.all()
    context = {"estudiantes": query}
    return render(request, "Estudiante/index.html", context)
    
def estudiante_create(request):
    if(request.method == "POST"):
        form = EstudianteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Clase:estudiante_home")
        else:
            form2 = EstudianteForm()
            return render(request, "Estudiante/create.html", {"error": form.errors, "form": form2})
    else:
        form = EstudianteForm()
        return render(request, "Estudiante/create.html", {"form": form})
    
def profesor_home(request):
    query = models.Profesor.objects.all()
    context = {"profesores": query}
    return render(request, "Profesor/index.html", context)

def profesor_create(request):
    if(request.method == "POST"):
        form = ProfesorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Clase:profesor_home")
        else:
            form2 = ProfesorForm()
            return render(request, "Profesor/create.html", {"error": form.errors, "form": form2})
    else:
        form = ProfesorForm()
        return render(request, "Profesor/create.html", {"form": form})
    
def curso_home(request):
    query = models.Curso.objects.all()
    context = {"cursos": query}
    return render(request, "Curso/index.html", context)

def curso_create(request):
    if(request.method == "POST"):
        form = CursoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Clase:curso_home")
        else:
            form2 = CursoForm()
            return render(request, "Curso/create.html", {"error": form.errors, "form": form2})
    else:
        form = CursoForm()
        return render(request, "Curso/create.html", {"form": form})

project/core/views.py
from django.shortcuts import render

def home(request):
    return render(request, "core/index.html")

project/Clase/templates/Comision/create.html
{% extends "core/base.html" %}
<style>
    ul {color:red;}
    li {color:blue;} 
</style>

{% block content %}
    {% if error %}
        <p style="color: blue; font-weight: bold"> ERROR: {{ error }}</p>
    {% endif %}
    <form method="post"> 
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
{% endblock content %}

project/Clase/templates/Comision/index.html
{% extends "core/base.html" %}

{% block title %}
    COMISION
{% endblock title %}

{% block content %}
    <a href="{% url 'Clase:comision_create' %}">Crear nueva Comision</a>
    {% for comision in comisiones %}
        <p>{{ comision.nombre }} | {{ comision.curso }} | {{ comision.profesor }}</p>
            {% for estudiante in comision.estudiante.all %}
                <p>{{ estudiante.nombre }}</p>
            {% endfor %}
    {% endfor %}
{% endblock content %}

project/Clase/templates/Curso/create.html
{% extends "core/base.html" %}

{% block content %}
    {% if error %}
        <p style="color: blue; font-weight: bold"> ERROR: {{ error }}</p>
    {% endif %}
    <form method="post"> 
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
{% endblock content %}

project/Clase/templates/Curso/index.html
{% extends "core/base.html" %}

{% block title %}
    Cursos
{% endblock title %}

{% block content %}
    <a href="{% url 'Clase:curso_create' %}">Registrar nuevo Curso</a>
    {% for curso in cursos %}
        <p>{{ curso.nombre }} </p>        
    {% endfor %}
{% endblock content %}

project/Clase/templates/Estudiante/index.html
{% extends "core/base.html" %}

{% block title %}
    Estudiantes
{% endblock title %}

{% block content %}
    <a href="{% url 'Clase:estudiante_create' %}">Añadir nuevo Estudiante</a>
    {% for estudiante in estudiantes %}
        <p>{{ estudiante.nombre }} </p>        
    {% endfor %}
{% endblock content %}

project/Clase/templates/Profesor/index.html
{% extends "core/base.html" %}

{% block title %}
    Profesores
{% endblock title %}

{% block content %}
    <a href="{% url 'Clase:profesor_create' %}">Añadir nuevo Profesor</a>
    {% for profesor in profesores %}
        <p>{{ profesor.nombre }} </p>        
    {% endfor %}
{% endblock content %}

project/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proyecto Coder</title>
</head>
    <body>
        {% block title %}
        {% endblock title %}
            <p style="color: black; font-weight: bold">Bienvenido a la Página Principal</p>
        {% block content %}
        {% endblock content %}
    
    </body>
</html>

project/core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}
    <h1>PÁGINA DE INICIO</h1>
{% endblock title %}

{% block content %}
    <ul>
        <li>
            <a href="{% url 'Clase:home' %}">Comisiones</a>
            
            <a href="{% url 'Clase:estudiante_home' %}">Estudiantes</a>

            <a href="{% url 'Clase:profesor_home' %}">Profesores</a>

            <a href="{% url 'Clase:curso_home' %}">Cursos</a>

        </li>
    </ul>
{% endblock content %}